"""empty message

Revision ID: f97bc3aee931
Revises: 
Create Date: 2020-03-11 19:26:21.943006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97bc3aee931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist_table = op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    venue_table = op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    show_table = op.create_table('show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id', 'start_time')
    )

    op.bulk_insert(
        venue_table, [
            {'name':'The Musical Hop',
             'address':'1015 Folsom Street',
             'city':'San Francisco',
             'state':'CA',
             'phone':'123-123-1234',
             'website':'https://www.themusicalhop.com',
             'facebook_link':'https://www.facebook.com/TheMusicalHop',
             'image_link':'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
             'genres':['Jazz', 'Reggae', 'Classical', 'Folk'],
             'seeking_talent':True,
             'seeking_description':'We are on the lookout for a local artist to play every two weeks. Please call us.'},

            {'name':'The Dueling Pianos Bar',
             'address':'335 Delancey Street',
             'city':'New York',
             'state':'NY',
             'phone':'914-003-1132',
             'website':'https://www.theduelingpianos.com',
             'facebook_link':'https://www.facebook.com/theduelingpianos',
             'image_link':'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
             'genres':['Classical', 'R&B', 'Hip-Hop'],
             'seeking_talent':False,
             'seeking_description':None},

            {'name':'Park Square Live Music & Coffee',
             'address':'34 Whiskey Moore Ave',
             'city':'San Francisco',
             'state':'CA',
             'phone':'415-000-1234',
             'website':'https://www.parksquarelivemusicandcoffee.com',
             'facebook_link':'https://www.facebook.com/ParkSquareLiveMusicAndCoffee',
             'image_link':'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80',
             'genres':['Rock n Roll', 'Jazz', 'Classical', 'Folk'],
             'seeking_talent':False,
             'seeking_description':None}
        ]
    )

    op.bulk_insert(
        artist_table, [
            {'name':'Guns N Petals',
             'city':'San Francisco',
             'state':'CA',
             'phone':'326-123-5000',
             'website':'https://www.gunsnpetalsband.com',
             'facebook_link':'https://www.facebook.com/GunsNPetals',
             'image_link':'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80',
             'genres':['Rock n Roll'],
             'seeking_venue':True,
             'seeking_description':'Looking for shows to perform at in the San Francisco Bay Area!'},

            {'name':'Matt Quevedo',
             'city':'New York',
             'state':'NY',
             'phone':'300-400-5000',
             'website':None,
             'facebook_link':'https://www.facebook.com/mattquevedo923251523',
             'image_link':'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80',
             'genres':['Jazz'],
             'seeking_venue':False,
             'seeking_description':None},

            {'name':'The Wild Sax Band',
             'city':'San Francisco',
             'state':'CA',
             'phone':'432-325-5432',
             'website':None,
             'facebook_link':None,
             'image_link':'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80',
             'genres':['Jazz', 'Classical'],
             'seeking_venue':False,
             'seeking_description':None}
        ]
    )

    op.bulk_insert(
        show_table, [
            {'artist_id':1,
             'venue_id':1,
             'start_time':'2019-05-21T21:30:00.000Z'},

            {'artist_id':2,
             'venue_id':3,
             'start_time':'2019-06-15T23:00:00.000Z'},

            {'artist_id':3,
             'venue_id':3,
             'start_time':'2035-04-01T20:00:00.000Z'},

            {'artist_id':3,
             'venue_id':3,
             'start_time':'2035-04-08T20:00:00.000Z'},

            {'artist_id':3,
             'venue_id':3,
             'start_time':'2035-04-15T20:00:00.000Z'}
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###
